//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Assessment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Armor.Web.Resources.Views.Assessment.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining.
        /// </summary>
        public static string PatientAssessmentsRemaining {
            get {
                return ResourceManager.GetString("PatientAssessmentsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (complete from now until April 5).
        /// </summary>
        public static string PatientAssessmentsText {
            get {
                return ResourceManager.GetString("PatientAssessmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Assessments.
        /// </summary>
        public static string PatientAssessmentsTitle {
            get {
                return ResourceManager.GetString("PatientAssessmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (complete before Intro Meeting).
        /// </summary>
        public static string PreAssessmentText {
            get {
                return ResourceManager.GetString("PreAssessmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Assessment Questionnaire.
        /// </summary>
        public static string PreAssessmentTitle {
            get {
                return ResourceManager.GetString("PreAssessmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (complete before Intro Meeting).
        /// </summary>
        public static string ProgramEvaluatorStage1Text {
            get {
                return ResourceManager.GetString("ProgramEvaluatorStage1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Evaluator Stage 1.
        /// </summary>
        public static string ProgramEvaluatorStage1Title {
            get {
                return ResourceManager.GetString("ProgramEvaluatorStage1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (complete after Intro Meeting).
        /// </summary>
        public static string ProgramEvaluatorStage2Text {
            get {
                return ResourceManager.GetString("ProgramEvaluatorStage2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Evaluator Stage 2.
        /// </summary>
        public static string ProgramEvaluatorStage2Title {
            get {
                return ResourceManager.GetString("ProgramEvaluatorStage2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (complete once all 25 patients have been assessed).
        /// </summary>
        public static string ProgramEvaluatorStage3Text {
            get {
                return ResourceManager.GetString("ProgramEvaluatorStage3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Evaluator Stage 3.
        /// </summary>
        public static string ProgramEvaluatorStage3Title {
            get {
                return ResourceManager.GetString("ProgramEvaluatorStage3Title", resourceCulture);
            }
        }
    }
}
