//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Assessment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PatientAssessment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientAssessment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Armor.Web.Resources.Views.Assessment.PatientAssessment", typeof(PatientAssessment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Age.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Which of the following other medication(s) is this patient currently taking? (Select all that apply).
        /// </summary>
        public static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misoprostol.
        /// </summary>
        public static string Question101 {
            get {
                return ResourceManager.GetString("Question101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proton pump inhibitor (eg, omeprazole, pantoprazole).
        /// </summary>
        public static string Question102 {
            get {
                return ResourceManager.GetString("Question102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2 receptor antagonist (eg, cimetadine, ranitidine).
        /// </summary>
        public static string Question103 {
            get {
                return ResourceManager.GetString("Question103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-dose ASA (&lt;300 mg/day).
        /// </summary>
        public static string Question104 {
            get {
                return ResourceManager.GetString("Question104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selective serotonin reuptake inhibitor (eg, citalopram, paroxetine).
        /// </summary>
        public static string Question105 {
            get {
                return ResourceManager.GetString("Question105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anticoagulant (eg, warfarin).
        /// </summary>
        public static string Question106 {
            get {
                return ResourceManager.GetString("Question106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corticosteroid (eg, prednisone).
        /// </summary>
        public static string Question107 {
            get {
                return ResourceManager.GetString("Question107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antiplatelet medication.
        /// </summary>
        public static string Question108 {
            get {
                return ResourceManager.GetString("Question108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. How would you categorize this patient’s GI risk?.
        /// </summary>
        public static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Question111 {
            get {
                return ResourceManager.GetString("Question111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string Question112 {
            get {
                return ResourceManager.GetString("Question112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Question113 {
            get {
                return ResourceManager.GetString("Question113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Your patient’s GI risk:.
        /// </summary>
        public static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13. Knowing this patient’s level of GI risk, what changes will you make to their OA medication(s)? (Check all that apply).
        /// </summary>
        public static string Question13 {
            get {
                return ResourceManager.GetString("Question13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaminophen.
        /// </summary>
        public static string Question131 {
            get {
                return ResourceManager.GetString("Question131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celecoxib.
        /// </summary>
        public static string Question1310 {
            get {
                return ResourceManager.GetString("Question1310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaminophen/tramadol.
        /// </summary>
        public static string Question1311 {
            get {
                return ResourceManager.GetString("Question1311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codeine (in combination with acetaminophen).
        /// </summary>
        public static string Question1312 {
            get {
                return ResourceManager.GetString("Question1312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 360 (codeine).
        /// </summary>
        public static string Question1312a {
            get {
                return ResourceManager.GetString("Question1312a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 360 (codeine).
        /// </summary>
        public static string Question1312b {
            get {
                return ResourceManager.GetString("Question1312b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tramadol.
        /// </summary>
        public static string Question1313 {
            get {
                return ResourceManager.GetString("Question1313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspirin (&gt;300 mg).
        /// </summary>
        public static string Question132 {
            get {
                return ResourceManager.GetString("Question132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diclofenac.
        /// </summary>
        public static string Question133 {
            get {
                return ResourceManager.GetString("Question133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diclofenac/misoprostol.
        /// </summary>
        public static string Question134 {
            get {
                return ResourceManager.GetString("Question134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 (diclofenac).
        /// </summary>
        public static string Question134a {
            get {
                return ResourceManager.GetString("Question134a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 (diclofenac).
        /// </summary>
        public static string Question134b {
            get {
                return ResourceManager.GetString("Question134b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibuprofen.
        /// </summary>
        public static string Question135 {
            get {
                return ResourceManager.GetString("Question135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1200mg/day.
        /// </summary>
        public static string Question135a {
            get {
                return ResourceManager.GetString("Question135a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;= 1200mg/day.
        /// </summary>
        public static string Question135b {
            get {
                return ResourceManager.GetString("Question135b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indomethacin.
        /// </summary>
        public static string Question136 {
            get {
                return ResourceManager.GetString("Question136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meloxicam.
        /// </summary>
        public static string Question137 {
            get {
                return ResourceManager.GetString("Question137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naproxen.
        /// </summary>
        public static string Question138 {
            get {
                return ResourceManager.GetString("Question138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naproxen—PPI.
        /// </summary>
        public static string Question139 {
            get {
                return ResourceManager.GetString("Question139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1000 (naproxen).
        /// </summary>
        public static string Question139a {
            get {
                return ResourceManager.GetString("Question139a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;= 1000 (naproxen).
        /// </summary>
        public static string Question139b {
            get {
                return ResourceManager.GetString("Question139b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change.
        /// </summary>
        public static string Question13a {
            get {
                return ResourceManager.GetString("Question13a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to:.
        /// </summary>
        public static string Question13b {
            get {
                return ResourceManager.GetString("Question13b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a gastroprotective agent.
        /// </summary>
        public static string Question13c {
            get {
                return ResourceManager.GetString("Question13c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Question13Other {
            get {
                return ResourceManager.GetString("Question13Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        public static string Question13Title1 {
            get {
                return ResourceManager.GetString("Question13Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose (mg/day).
        /// </summary>
        public static string Question13Title2 {
            get {
                return ResourceManager.GetString("Question13Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Sex.
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Question21 {
            get {
                return ResourceManager.GetString("Question21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Question22 {
            get {
                return ResourceManager.GetString("Question22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Type of OA (select all that apply).
        /// </summary>
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cervical.
        /// </summary>
        public static string Question31 {
            get {
                return ResourceManager.GetString("Question31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dorsal.
        /// </summary>
        public static string Question32 {
            get {
                return ResourceManager.GetString("Question32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumbar.
        /// </summary>
        public static string Question33 {
            get {
                return ResourceManager.GetString("Question33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Question34 {
            get {
                return ResourceManager.GetString("Question34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip.
        /// </summary>
        public static string Question35 {
            get {
                return ResourceManager.GetString("Question35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knee.
        /// </summary>
        public static string Question36 {
            get {
                return ResourceManager.GetString("Question36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Is this patient overweight (ie, BMI &gt;25).
        /// </summary>
        public static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Question41 {
            get {
                return ResourceManager.GetString("Question41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Question42 {
            get {
                return ResourceManager.GetString("Question42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Smoking status.
        /// </summary>
        public static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active smoker.
        /// </summary>
        public static string Question51 {
            get {
                return ResourceManager.GetString("Question51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex-smoker (within the past 10 years).
        /// </summary>
        public static string Question52 {
            get {
                return ResourceManager.GetString("Question52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-smoker.
        /// </summary>
        public static string Question53 {
            get {
                return ResourceManager.GetString("Question53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Average number of alcoholic drinks per week.
        /// </summary>
        public static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Does this patient use illicit/recreational drugs?.
        /// </summary>
        public static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Question71 {
            get {
                return ResourceManager.GetString("Question71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Question72 {
            get {
                return ResourceManager.GetString("Question72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. History of.
        /// </summary>
        public static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomplicated peptic ulcer.
        /// </summary>
        public static string Question81 {
            get {
                return ResourceManager.GetString("Question81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyspepsia.
        /// </summary>
        public static string Question82 {
            get {
                return ResourceManager.GetString("Question82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GERD.
        /// </summary>
        public static string Question83 {
            get {
                return ResourceManager.GetString("Question83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleeding peptic ulcer.
        /// </summary>
        public static string Question84 {
            get {
                return ResourceManager.GetString("Question84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H pylori infection treated.
        /// </summary>
        public static string Question85 {
            get {
                return ResourceManager.GetString("Question85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H pylori infection untreated.
        /// </summary>
        public static string Question86 {
            get {
                return ResourceManager.GetString("Question86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Which of the following medication(s) is this patient currently taking to manage their OA symptoms? (Select all that apply).
        /// </summary>
        public static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaminophen.
        /// </summary>
        public static string Question91 {
            get {
                return ResourceManager.GetString("Question91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celecoxib.
        /// </summary>
        public static string Question910 {
            get {
                return ResourceManager.GetString("Question910", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaminophen/tramadol.
        /// </summary>
        public static string Question911 {
            get {
                return ResourceManager.GetString("Question911", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codeine (in combination with acetaminophen).
        /// </summary>
        public static string Question912 {
            get {
                return ResourceManager.GetString("Question912", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 360 (codeine).
        /// </summary>
        public static string Question912a {
            get {
                return ResourceManager.GetString("Question912a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 360 (codeine).
        /// </summary>
        public static string Question912b {
            get {
                return ResourceManager.GetString("Question912b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tramadol.
        /// </summary>
        public static string Question913 {
            get {
                return ResourceManager.GetString("Question913", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspirin (&gt;300 mg).
        /// </summary>
        public static string Question92 {
            get {
                return ResourceManager.GetString("Question92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diclofenac.
        /// </summary>
        public static string Question93 {
            get {
                return ResourceManager.GetString("Question93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diclofenac/misoprostol.
        /// </summary>
        public static string Question94 {
            get {
                return ResourceManager.GetString("Question94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 (diclofenac).
        /// </summary>
        public static string Question94a {
            get {
                return ResourceManager.GetString("Question94a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 (diclofenac).
        /// </summary>
        public static string Question94b {
            get {
                return ResourceManager.GetString("Question94b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibuprofen.
        /// </summary>
        public static string Question95 {
            get {
                return ResourceManager.GetString("Question95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1200mg/day.
        /// </summary>
        public static string Question95a {
            get {
                return ResourceManager.GetString("Question95a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;= 1200mg/day.
        /// </summary>
        public static string Question95b {
            get {
                return ResourceManager.GetString("Question95b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indomethacin.
        /// </summary>
        public static string Question96 {
            get {
                return ResourceManager.GetString("Question96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meloxicam.
        /// </summary>
        public static string Question97 {
            get {
                return ResourceManager.GetString("Question97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naproxen.
        /// </summary>
        public static string Question98 {
            get {
                return ResourceManager.GetString("Question98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naproxen—PPI.
        /// </summary>
        public static string Question99 {
            get {
                return ResourceManager.GetString("Question99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1000 (naproxen).
        /// </summary>
        public static string Question99a {
            get {
                return ResourceManager.GetString("Question99a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;= 1000 (naproxen).
        /// </summary>
        public static string Question99b {
            get {
                return ResourceManager.GetString("Question99b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Question9Other {
            get {
                return ResourceManager.GetString("Question9Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        public static string Question9Title1 {
            get {
                return ResourceManager.GetString("Question9Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose (mg/day).
        /// </summary>
        public static string Question9Title2 {
            get {
                return ResourceManager.GetString("Question9Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Assessment.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;To be completed by physician for patients who meet the following criteria:&lt;/h3&gt;
        ///&lt;div class=&quot;criteria&quot;&gt;
        ///    &lt;ul&gt;
        ///        &lt;li&gt;Diagnosis of osteoarthritis&lt;/li&gt;
        ///        &lt;li&gt;Aged 18 years or older&lt;/li&gt;
        ///        &lt;li&gt;Has pain that interferes with normal daily activities&lt;/li&gt;
        ///        &lt;li&gt;Has an indication for NSAID treatment&lt;/li&gt;
        ///    &lt;/ul&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string TopTextBlur {
            get {
                return ResourceManager.GetString("TopTextBlur", resourceCulture);
            }
        }
    }
}
