//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PreAssessment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PreAssessment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Armor.Web.Resources.Views.Assessment.PreAssessment", typeof(PreAssessment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;
        ///                &lt;li&gt;Diagnosis of osteoarthritis&lt;/li&gt;
        ///                &lt;li&gt;Aged 18 years or older&lt;/li&gt;
        ///                &lt;li&gt;Has pain that interferes with normal daily activities&lt;/li&gt;
        ///                &lt;li&gt;Has an indication for NSAID treatment&lt;/li&gt;
        ///            &lt;/ul&gt;.
        /// </summary>
        public static string BeforeQ3Bullets {
            get {
                return ResourceManager.GetString("BeforeQ3Bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following questions apply only to the patients in your practice who meet the following criteria:.
        /// </summary>
        public static string HeaderBeforeQ3 {
            get {
                return ResourceManager.GetString("HeaderBeforeQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. What percentage of patients in your practice have OA?.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. What percentage of these patients have OA in the following sites (% does not need to add up to 100% as patients may have OA in more than one site):.
        /// </summary>
        public static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cervical.
        /// </summary>
        public static string Question101 {
            get {
                return ResourceManager.GetString("Question101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dorsal.
        /// </summary>
        public static string Question102 {
            get {
                return ResourceManager.GetString("Question102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumbar.
        /// </summary>
        public static string Question103 {
            get {
                return ResourceManager.GetString("Question103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Question104 {
            get {
                return ResourceManager.GetString("Question104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip.
        /// </summary>
        public static string Question105 {
            get {
                return ResourceManager.GetString("Question105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knee.
        /// </summary>
        public static string Question106 {
            get {
                return ResourceManager.GetString("Question106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. What percentage of this patients would you categorize as being at low, moderate, and high risk of GI complications with NSAID use? (Percentages should add up to 100%):.
        /// </summary>
        public static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low risk.
        /// </summary>
        public static string Question111 {
            get {
                return ResourceManager.GetString("Question111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate risk.
        /// </summary>
        public static string Question112 {
            get {
                return ResourceManager.GetString("Question112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High risk.
        /// </summary>
        public static string Question113 {
            get {
                return ResourceManager.GetString("Question113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. Which medications do you typically prescribe for these patients in the following GI risk categories (select all that apply):.
        /// </summary>
        public static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaminophen.
        /// </summary>
        public static string Question121 {
            get {
                return ResourceManager.GetString("Question121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celecoxib.
        /// </summary>
        public static string Question1210 {
            get {
                return ResourceManager.GetString("Question1210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetaminophen/tramadol.
        /// </summary>
        public static string Question1211 {
            get {
                return ResourceManager.GetString("Question1211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codeine (in combination with acetaminophen).
        /// </summary>
        public static string Question1212 {
            get {
                return ResourceManager.GetString("Question1212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tramadol.
        /// </summary>
        public static string Question1213 {
            get {
                return ResourceManager.GetString("Question1213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Question1214 {
            get {
                return ResourceManager.GetString("Question1214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspirin (&gt;300 mg).
        /// </summary>
        public static string Question122 {
            get {
                return ResourceManager.GetString("Question122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diclofenac.
        /// </summary>
        public static string Question123 {
            get {
                return ResourceManager.GetString("Question123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diclofenac/misoprostol.
        /// </summary>
        public static string Question124 {
            get {
                return ResourceManager.GetString("Question124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibuprofen.
        /// </summary>
        public static string Question125 {
            get {
                return ResourceManager.GetString("Question125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indomethacin.
        /// </summary>
        public static string Question126 {
            get {
                return ResourceManager.GetString("Question126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meloxicam.
        /// </summary>
        public static string Question127 {
            get {
                return ResourceManager.GetString("Question127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naproxen.
        /// </summary>
        public static string Question128 {
            get {
                return ResourceManager.GetString("Question128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naproxen/PPI.
        /// </summary>
        public static string Question129 {
            get {
                return ResourceManager.GetString("Question129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication.
        /// </summary>
        public static string Question12Header1 {
            get {
                return ResourceManager.GetString("Question12Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low GI risk.
        /// </summary>
        public static string Question12Header2 {
            get {
                return ResourceManager.GetString("Question12Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate GI risk.
        /// </summary>
        public static string Question12Header3 {
            get {
                return ResourceManager.GetString("Question12Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High GI risk.
        /// </summary>
        public static string Question12Header4 {
            get {
                return ResourceManager.GetString("Question12Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. What percentage of your patients with OA are taking an NSAID?.
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. What percentage of these patients are older than 60 years of age?.
        /// </summary>
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. What percentage of these patients are overweight?.
        /// </summary>
        public static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. What percentage of these patients are:.
        /// </summary>
        public static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active smokers?.
        /// </summary>
        public static string Question51 {
            get {
                return ResourceManager.GetString("Question51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex-smokers?.
        /// </summary>
        public static string Question52 {
            get {
                return ResourceManager.GetString("Question52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-smokers.
        /// </summary>
        public static string Question53 {
            get {
                return ResourceManager.GetString("Question53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. What percentage of these patients are taking low-dose ASA (&lt;300 mg/day) for CV protection?.
        /// </summary>
        public static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. What percentage of these patients are taking a corticosteroid?.
        /// </summary>
        public static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. What percentage of these patients are taking an anticoagulant medication?.
        /// </summary>
        public static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. What percentage of these patients have a history of:.
        /// </summary>
        public static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomplicated peptic ulcer.
        /// </summary>
        public static string Question91 {
            get {
                return ResourceManager.GetString("Question91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GERD.
        /// </summary>
        public static string Question92 {
            get {
                return ResourceManager.GetString("Question92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyspepsia.
        /// </summary>
        public static string Question93 {
            get {
                return ResourceManager.GetString("Question93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleeding peptic ulcer.
        /// </summary>
        public static string Question94 {
            get {
                return ResourceManager.GetString("Question94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;em&gt;H pylori&lt;/em&gt; infection.
        /// </summary>
        public static string Question95 {
            get {
                return ResourceManager.GetString("Question95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Assessment Questionnaire.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
