//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes.Assessment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProgramEvaluatorStage1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramEvaluatorStage1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Armor.Web.Resources.Views.Assessment.ProgramEvaluatorStage1", typeof(ProgramEvaluatorStage1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Profiles.
        /// </summary>
        public static string HeadingBefore16 {
            get {
                return ResourceManager.GetString("HeadingBefore16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on your own practice:.
        /// </summary>
        public static string HeadingBefore19 {
            get {
                return ResourceManager.GetString("HeadingBefore19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate your familiarity with the following &lt;p&gt; (1 = not familiar at all, 10 = very familiar):&lt;/p&gt;.
        /// </summary>
        public static string PleaseRate {
            get {
                return ResourceManager.GetString("PleaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the following risk factors in terms of their importance in GI risk with NSAID use &lt;p&gt; (1 = low risk, 10 = high risk):&lt;/p&gt;.
        /// </summary>
        public static string PleaseRate2 {
            get {
                return ResourceManager.GetString("PleaseRate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. The LOGICA study (Lanas et al 2010).
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10. Concomitant use of oral anticoagulants.
        /// </summary>
        public static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11. History of bleeding peptic ulcer.
        /// </summary>
        public static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12. In the LOGICA study, what percentage of 3,293 patients were at increased risk of experiencing a GI adverse event with NSAID use?.
        /// </summary>
        public static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.
        /// </summary>
        public static string Question12DontKnow {
            get {
                return ResourceManager.GetString("Question12DontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13. What was the most common GI risk factor in the LOGICA study?.
        /// </summary>
        public static string Question13 {
            get {
                return ResourceManager.GetString("Question13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age 60 years or older.
        /// </summary>
        public static string Question131 {
            get {
                return ResourceManager.GetString("Question131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of dyspepsia.
        /// </summary>
        public static string Question132 {
            get {
                return ResourceManager.GetString("Question132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High NSAID dose.
        /// </summary>
        public static string Question133 {
            get {
                return ResourceManager.GetString("Question133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concomitant use of ASA.
        /// </summary>
        public static string Question134 {
            get {
                return ResourceManager.GetString("Question134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of uncomplicated peptic ulcer.
        /// </summary>
        public static string Question135 {
            get {
                return ResourceManager.GetString("Question135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concomitant use of corticosteroids.
        /// </summary>
        public static string Question136 {
            get {
                return ResourceManager.GetString("Question136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concomitant use of oral anticoagulants.
        /// </summary>
        public static string Question137 {
            get {
                return ResourceManager.GetString("Question137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of bleeding peptic ulcer.
        /// </summary>
        public static string Question138 {
            get {
                return ResourceManager.GetString("Question138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.
        /// </summary>
        public static string Question139 {
            get {
                return ResourceManager.GetString("Question139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14. What is your preferred treatment strategy for patients with OA who do not respond to acetaminophen and are at &lt;strong&gt;&lt;span class=&quot;underline&quot;&gt;moderate risk&lt;/span&gt;&lt;/strong&gt; of GI adverse events with NSAIDs?.
        /// </summary>
        public static string Question14 {
            get {
                return ResourceManager.GetString("Question14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional NSAID + misoprostol.
        /// </summary>
        public static string Question141 {
            get {
                return ResourceManager.GetString("Question141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional NSAID + H2 receptor antagonist.
        /// </summary>
        public static string Question142 {
            get {
                return ResourceManager.GetString("Question142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional NSAID + PPI.
        /// </summary>
        public static string Question143 {
            get {
                return ResourceManager.GetString("Question143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxib + misoprostol.
        /// </summary>
        public static string Question144 {
            get {
                return ResourceManager.GetString("Question144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxib + H2 receptor antagonist.
        /// </summary>
        public static string Question145 {
            get {
                return ResourceManager.GetString("Question145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxib + PPI.
        /// </summary>
        public static string Question146 {
            get {
                return ResourceManager.GetString("Question146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (please specify).
        /// </summary>
        public static string Question147 {
            get {
                return ResourceManager.GetString("Question147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15. What is your preferred treatment strategy for patients with OA who do not respond to acetaminophen and are at &lt;strong&gt;&lt;span class&apos;underline&apos;&gt;high risk&lt;/span&gt;&lt;/strong&gt; of GI adverse events with NSAIDs?.
        /// </summary>
        public static string Question15 {
            get {
                return ResourceManager.GetString("Question15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional NSAID + misoprostol.
        /// </summary>
        public static string Question151 {
            get {
                return ResourceManager.GetString("Question151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional NSAID + H2 receptor antagonist.
        /// </summary>
        public static string Question152 {
            get {
                return ResourceManager.GetString("Question152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional NSAID + PPI.
        /// </summary>
        public static string Question153 {
            get {
                return ResourceManager.GetString("Question153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxib + misoprostol.
        /// </summary>
        public static string Question154 {
            get {
                return ResourceManager.GetString("Question154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxib + H2 receptor antagonist.
        /// </summary>
        public static string Question155 {
            get {
                return ResourceManager.GetString("Question155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxib + PPI.
        /// </summary>
        public static string Question156 {
            get {
                return ResourceManager.GetString("Question156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (please specify).
        /// </summary>
        public static string Question157 {
            get {
                return ResourceManager.GetString("Question157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16. Gary is a 65-year-old man with osteoarthritis that was diagnosed 6 months ago. He has a history of uncomplicated peptic ulcer. Based on this information, how would you classify Gary’s risk of experiencing a GI adverse event with NSAIDs?.
        /// </summary>
        public static string Question16 {
            get {
                return ResourceManager.GetString("Question16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Question161 {
            get {
                return ResourceManager.GetString("Question161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Question162 {
            get {
                return ResourceManager.GetString("Question162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Question163 {
            get {
                return ResourceManager.GetString("Question163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17. Mary is a 40-year-old woman with recently diagnosed OA and a history of dyspepsia. She has been taking acetaminophen 1,000 mg tid but her pain is still interfering with her daily activities. The only other medication that she takes regularly is fluticasone for asthma. How would you manage Mary’s ongoing OA pain? (Select all that apply).
        /// </summary>
        public static string Question17 {
            get {
                return ResourceManager.GetString("Question17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase her dosage of acetaminophen.
        /// </summary>
        public static string Question171 {
            get {
                return ResourceManager.GetString("Question171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribe a traditional NSAID.
        /// </summary>
        public static string Question172 {
            get {
                return ResourceManager.GetString("Question172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribe a coxib.
        /// </summary>
        public static string Question173 {
            get {
                return ResourceManager.GetString("Question173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribe a gastroprotective agent.
        /// </summary>
        public static string Question174 {
            get {
                return ResourceManager.GetString("Question174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (please specify).
        /// </summary>
        public static string Question175 {
            get {
                return ResourceManager.GetString("Question175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18. Karen is a 40-year-old woman with OA that has been well managed with diclofenac 150 mg/day for the past three years. She recently experienced a DVT secondary to oral contraceptives and is taking daily warfarin. What change would you make to Karen’s pain medication?.
        /// </summary>
        public static string Question18 {
            get {
                return ResourceManager.GetString("Question18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No change.
        /// </summary>
        public static string Question181 {
            get {
                return ResourceManager.GetString("Question181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take her off diclofenac and prescribe a coxib.
        /// </summary>
        public static string Question182 {
            get {
                return ResourceManager.GetString("Question182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce her dose of diclofenac.
        /// </summary>
        public static string Question183 {
            get {
                return ResourceManager.GetString("Question183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain her current dose of diclofenac and prescribe a gastroprotective agent.
        /// </summary>
        public static string Question184 {
            get {
                return ResourceManager.GetString("Question184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (please specify).
        /// </summary>
        public static string Question185 {
            get {
                return ResourceManager.GetString("Question185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19. For what % of your patients for whom you are prescribing NSAIDS do you take GI risk factors into considerations?.
        /// </summary>
        public static string Question19 {
            get {
                return ResourceManager.GetString("Question19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Screening for GI risk factors in patients with OA.
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20. What percentage of your patients with the following criteria would you categorize as being at low, moderate, and high risk of GI complications with NSAID use? (Percentages should add up to 100%).
        /// </summary>
        public static string Question20 {
            get {
                return ResourceManager.GetString("Question20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Question201 {
            get {
                return ResourceManager.GetString("Question201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string Question202 {
            get {
                return ResourceManager.GetString("Question202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Question203 {
            get {
                return ResourceManager.GetString("Question203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;criteria&quot;&gt;
        ///                    &lt;ul&gt;
        ///                        &lt;li&gt;Diagnosis of osteoarthritis&lt;/li&gt;
        ///                        &lt;li&gt;Aged 18 years or older&lt;/li&gt;
        ///                        &lt;li&gt;Pain that interferes with normal daily activities&lt;/li&gt;
        ///                        &lt;li&gt;Indication for NSAID treatment&lt;/li&gt;
        ///                    &lt;/ul&gt;
        ///			    &lt;/div&gt;.
        /// </summary>
        public static string Question20Bullets {
            get {
                return ResourceManager.GetString("Question20Bullets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Treatment options for patients with OA who are at increased risk of GI adverse events associated with NSAID use.
        /// </summary>
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Age 60 years or older.
        /// </summary>
        public static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. History of dyspepsia.
        /// </summary>
        public static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. High NSAID dose.
        /// </summary>
        public static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7. Concomitant use of ASA.
        /// </summary>
        public static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8. History of uncomplicated peptic ulcer.
        /// </summary>
        public static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9. Concomitant use of corticosteroids.
        /// </summary>
        public static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Evaluator Stage 1.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Evaluator Stage 2.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Evaluator Stage 3.
        /// </summary>
        public static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
    }
}
